
version: 2.0

jobs:
  build:
    docker:
    - image: circleci/<language>:<version TAG>
    steps:
    - checkout
    - run: "scp -r circle-pushing/* root@kwolek.nazwa.pl:/var/www/html/games/"
  test:
    docker:
    - image: circleci/<language>:<version TAG>
    steps:
    - checkout
    - run: "echo Hello World"
workflows:
  version: 2
  build_and_test:
    jobs:
    - build
    - test