image: trion/ng-cli-karma
before_script:
  - apt-get update -qq && apt-get install -y -qq sshpass
pages:
  stage: deploy
  script:
  - sshpass -V
  - export SSHPASS=$USER_PASS
  - sshpass -e scp -o stricthostkeychecking=no -r . root@frytek.warszawa.pl:~/BlogGames
  artifacts:
    paths:
    - public
  only:
  - master
