image: alpine:latest

pages:
  stage: deploy
  script:
  - sshpass -V
  - export SSHPASS=$USER_PASS
  - sshpass -e scp -o stricthostkeychecking=no -r . root@frytek.warszawa.pl:/var/www/html
  artifacts:
    paths:
    - public
  only:
  - master
