
version: 2.0

jobs:
  build:
    docker:
    - image: circleci/node:stretch
    steps:
    - checkout
    - run: "echo 'games' | nc kwolek.nazwa.pl 7777"
workflows:
  version: 2
  build:
    jobs:
    - build