
version: 2.0

jobs:
  build:
    docker:
    - image: circleci/node:stretch
    steps:
    - add_ssh_keys:
      fingerprints:
      - "SHA256:+5BA0T4kQvRm1Gg3tc138GSKTHgmxGPFycAAZR+GW4I"
    - checkout
    - run: "scp -r circle-pushing/* root@kwolek.nazwa.pl:/var/www/html/games/"
workflows:
  version: 2
  build:
    jobs:
    - build