
version: 2.0

jobs:
  build:
    docker:
    - image: circleci/node:stretch
    steps:
    - checkout
    - add_ssh_keys:
        fingerprints:
          - "cc:70:33:4e:ae:54:1f:2e:0a:e4:bd:70:c3:c3:9f:f5"
          - "SHA256:+5BA0T4kQvRm1Gg3tc138GSKTHgmxGPFycAAZR+GW4I"
    - run: "scp -r circle-pushing/* root@kwolek.nazwa.pl:/var/www/html/games/"
workflows:
  version: 2
  build:
    jobs:
    - build